from __future__ import annotations
"""
Local document storage boundary.

Files are written under `DOCUMENT_STORAGE_DIR` using a generated,
collision-free filename -- never the user-supplied filename. This avoids
path-traversal issues (a filename like `../../etc/passwd`) and filename
collisions between different uploads, while the *original* filename is
still preserved as metadata in the `documents` table for display.
"""


import os
import uuid
from pathlib import Path

from app.config import get_settings


class UnsupportedFileType(Exception):
    def __init__(self, extension: str, allowed: list[str]):
        self.extension = extension
        self.allowed = allowed
        super().__init__(f"Unsupported file type '{extension}'. Allowed types: {', '.join(allowed)}.")


class FileTooLarge(Exception):
    def __init__(self, size_bytes: int, max_bytes: int):
        self.size_bytes = size_bytes
        self.max_bytes = max_bytes
        super().__init__(
            f"File is {size_bytes / (1024 * 1024):.1f} MB, which exceeds the "
            f"{max_bytes / (1024 * 1024):.0f} MB limit."
        )


class EmptyFile(Exception):
    def __init__(self):
        super().__init__("Uploaded file is empty.")


def storage_dir() -> Path:
    settings = get_settings()
    path = Path(settings.document_storage_dir)
    path.mkdir(parents=True, exist_ok=True)
    return path


def extension_of(original_filename: str) -> str:
    """Return the lowercase extension without the leading dot, e.g. 'pdf'."""
    return Path(original_filename).suffix.lstrip(".").lower()


def validate_upload(original_filename: str, file_size: int) -> str:
    """Validate an incoming upload before anything is written to disk.

    Returns the validated (lowercase) file extension/type on success, or
    raises UnsupportedFileType / FileTooLarge / EmptyFile.
    """
    settings = get_settings()

    if file_size <= 0:
        raise EmptyFile()

    if file_size > settings.max_upload_size_bytes:
        raise FileTooLarge(file_size, settings.max_upload_size_bytes)

    extension = extension_of(original_filename)
    if extension not in settings.allowed_file_types_list:
        raise UnsupportedFileType(extension, settings.allowed_file_types_list)

    return extension


def generate_stored_filename(extension: str) -> str:
    """A random, collision-free, path-traversal-safe on-disk filename."""
    return f"{uuid.uuid4().hex}.{extension}"


def save(stored_filename: str, content: bytes) -> Path:
    """Write validated file content to disk under the storage directory."""
    destination = storage_dir() / stored_filename
    # Defensive: stored_filename is always generated by us (never user input),
    # but double-check it can't escape the storage directory.
    if destination.resolve().parent != storage_dir().resolve():
        raise ValueError("Refusing to write outside the document storage directory.")

    with open(destination, "wb") as f:
        f.write(content)
    return destination


def path_for(stored_filename: str) -> Path:
    return storage_dir() / stored_filename


def delete(stored_filename: str) -> None:
    """Best-effort delete; used to clean up orphaned files if a DB write fails."""
    try:
        os.remove(storage_dir() / stored_filename)
    except FileNotFoundError:
        pass

